"""Central configuration for NAS experiments."""

SEARCH_ITERATIONS = 20
CANDIDATE_EPOCHS = 3
FINAL_EPOCHS = 10
BATCH_SIZE = 128
LEARNING_RATE = 1e-3
PARAMETER_PENALTY = 0.10
MAX_PARAMETERS = 300_000
RANDOM_SEED = 42
RESULTS_DIR = "results"
